SELECT * FROM IDBUSER.RMS_DCC2EIP WHERE RMS_ID IS NOT NULL ORDER BY RMS_INSDT

update IDBUSER.RMS_DCC2EIP SET EIP_STATUS = '已簽核', EIP_CREATEDT = SYSDATE
WHERE RMS_ID = 'd6684807da1f427'

UPDATE IDBUSER.RMS_DCC2EIP SET EIP_STATUS = '否決', EIP_CREATEDT = SYSDATE, DECISION_USER = '王大明', DECISION_COMMENT = '測試'
WHERE RMS_ID = '3452dfd6b4ee4d7'

UPDATE IDBUSER.RMS_DCC2EIP SET EIP_STATUS = '審核中', EIP_CREATEDT = SYSDATE
WHERE RMS_ID = 'a76e66be69da4c2'

UPDATE IDBUSER.RMS_DCC2EIP SET RMS_ID = NULL, RMS_DCCNO = 'DELETED', RMS_DCCNAME = 'DELETED_DOCUMENT', EIP_CREATEDT = SYSDATE, EIP_STATUS = '作廢', DECISION_USER = '王巨成', DECISION_COMMENT = '測試文件' WHERE RMS_INSDT < SYSDATE;


UPDATE IDBUSER.RMS_DCC2EIP SET RMS_ID = NULL, RMS_DCCNO = 'DELETED', RMS_DCCNAME = 'DELETED_DOCUMENT', EIP_CREATEDT = SYSDATE, EIP_STATUS = '作廢', DECISION_USER = '王巨成', DECISION_COMMENT = '測試文件'
WHERE RMS_ID IN ('d430a5eeeb9b4c7');

SELECT * from IDBUSER.RMS_DCC2EIP WHERE RMS_ID IS NOT NULL AND EIP_STATUS IS NOT NULL ORDER BY EIP_CREATEDT DESC